{% set name = "rattler-build" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 802dd6af0189c6a6fa9d5d2ada52fd6ed0e42f7ea473f760166a06b1fcc3ef5d

build:
  script:
    # Unix recipe
    - export OPENSSL_DIR="$PREFIX"                                                      # [unix]
    - cargo install --locked --bin rattler-build --root ${PREFIX} --path . --no-track   # [unix]
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # [unix]
    # Win recipe
    - cargo install --locked --bin rattler-build --root %PREFIX% --path . --no-track       # [win]
    - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml   # [win]
  number: 0
  # disable binary prefix detection, because rattler-build encodes the old `anaconda1anaconda2anaconda3` prefix
  # somewhere to make old packages installable. In other words, conda-build finds a false-positive here.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]

test:
  commands:
    - rattler-build --help

about:
  home: https://github.com/prefix-dev/rattler-build
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
  description: |
    The rattler-build tooling and library creates cross-platform relocatable binaries / packages 
    from a simple recipe format.
    The recipe format is heavily inspired by conda-build and boa, and the output of a regular
    rattler-build run is a package that can be installed using mamba, conda or rattler.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - CONDA_BUILD_LICENSE.txt
  doc_url: https://prefix-dev.github.io/rattler-build

extra:
  recipe-maintainers:
    - nichmor
    - wolfv
    - pavelzw
    - '0xbe7a'
